### ISSUE TITLE
"The MetadataAddress or Authority must use HTTPS unless disabled..." on website launch

### ISSUE THREAD

**Issue by arbrctb** [MarcelMeurer/Azure-Starter-for-WVD#2]
The following .NET error appears when launching the website:

Server Error in '/' Application.

The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.

**Comment by pgjones67** [comment]
I work with @arbrctb  - would be great if we could get an idea on this one, as would to deploy within our production environment, thus would be interested in licensing. 

thanks in advance.

**Comment by MarcelMeurer** [comment]
Hi. Have you configured the web app before starting to use it?

**Comment by MarcelMeurer** [comment]
Or let us have a Teams call. You can reach me out using: Marcel.Meurer@sepago.de

**Comment by pgjones67** [comment]
Hi, thanks for the response, could we do a Teams call tomorrow at all - we'll fit around your availability.

**Comment by MarcelMeurer** [comment]
Sounds good. Feel free to send me a meeting request. I'm available after 2pm (your time zone).

Please use my address Marcel.Meurer@sepago.de - I will delete part of the threats later.

**Comment by MarcelMeurer** [comment]
> The following .NET error appears when launching the website:
> 
> Server Error in '/' Application.
> 
> The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> Exception Details: System.InvalidOperationException: The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.

This error message is expected if you have not configured the web-app right now. Unfortunately, a service principal cannot be generated with the ARM deployment of the web-app. So please start to configure the web-app here: 

https://github.com/MarcelMeurer/Azure-Starter-for-WVD#create-a-service-principal

**Comment by pgjones67** [comment]
Thanks Marcel, will do.



Regards,

--Paul

On 6 Aug 2020, at 17:49, Marcel <notifications@github.com> wrote:

﻿

Sounds good. Feel free to send me a meeting request. I'm available after 2pm (your time zone).

Please use my address Marcel.Meurer@sepago.de<mailto:Marcel.Meurer@sepago.de> - I will delete part of the threats later.
