### ISSUE TITLE
FeatureRequest - Exempt individual machines from autoDeallocate

### ISSUE THREAD

**Issue by biacz** [MarcelMeurer/Azure-Starter-for-WVD#4]
Hey Marcel,

would it be possible to supply a list of machines that are exempt from the autoDeallocation?

best, Niko

**Comment by MarcelMeurer** [comment]
Hi Niko.

With the newest version, you can ignore VMs from being deallocated. 

Set a tag to the VM and set it to "1". The Tag name should be "WVD.IgnoreShutdown"
